"""gen_spellbook.py -- Two-tier spellbook hub with rarity filter.

Cast a Working -> Sphere Hub (Common/Uncommon/Rare/Very Rare/Close)
-> Paged spells (3 per page, alphabetical, Close returns to hub)

Ported from mom-base-clean. Called from ctp2_generator.main().
"""
import csv
from pathlib import Path

# Injected at module init by the caller
MOD_POLICY = {}
MOMJR = Path(".")
SCENARIO = Path(".")
_write_rel = None
_policy_csv_rows = None


def init(mod_policy, momjr, scenario, write_rel, policy_csv_rows):
    """Inject dependencies from the orchestrator."""
    global MOD_POLICY, MOMJR, SCENARIO, _write_rel, _policy_csv_rows
    MOD_POLICY = mod_policy
    MOMJR = momjr
    SCENARIO = scenario
    _write_rel = write_rel
    _policy_csv_rows = policy_csv_rows


SPELLBOOK_SPHERES = ["life", "nature", "sorcery", "death", "chaos"]
SPELLBOOK_CAST_SLC_REL = "default/gamedata/mom_spellbook_cast.slc"
SPELLBOOK_SPHERE_SLC_REL = {
    s: f"default/gamedata/mom_spellbook_{s}.slc" for s in SPELLBOOK_SPHERES
}

RARITY_ORDER = ["common", "uncommon", "rare", "very rare"]
RARITY_LABELS = {"common": "Common", "uncommon": "Uncommon", "rare": "Rare", "very rare": "Very Rare"}
RARITY_KEYS = {"common": "COMMON", "uncommon": "UNCOMMON", "rare": "RARE", "very rare": "VERY_RARE"}


def emit_spellbook_pages() -> tuple[int, int]:
    """Emit per-sphere spellbook SLIC files: two-tier navigation.

    Tier 1: Hub alertbox per sphere with rarity filter buttons.
    Tier 2: Paged alertboxes per (sphere, rarity) with 3 spells + prev/next.

    Returns (total_pages, total_spells) across all 5 spheres.
    """
    rescale_cfg = MOD_POLICY["spellbook"]["cost_rescale"]
    rescale_factor = rescale_cfg["rescale_factor"]
    min_cost = rescale_cfg["min_cost"]
    max_cost = rescale_cfg["max_cost"]
    rarity_factors = rescale_cfg.get("rarity_factors", {})

    spells_path = MOMJR / "spells.csv"
    with open(spells_path, newline="", encoding="utf-8-sig") as fh:
        all_spells = list(csv.DictReader(fh))

    by_sphere: dict[str, list[dict]] = {s: [] for s in SPELLBOOK_SPHERES}
    for row in all_spells:
        sphere = row["sphere"].strip().lower()
        if sphere not in by_sphere:
            continue
        effect_kind = row["effect_kind"].strip()
        overland_cost = int(row["overland_cost"].strip() or "0")
        if effect_kind == "flavour" or overland_cost <= 0:
            continue
        rarity = row.get("rarity", "").lower().strip()
        factor = rarity_factors.get(rarity, rescale_factor)
        shipped_cost = max(min_cost, min(max_cost, int(overland_cost * factor)))
        row["_shipped_cost"] = shipped_cost
        row["_research_cost_int"] = int(row["research_cost"].strip() or "0")
        row["_rarity"] = rarity
        by_sphere[sphere].append(row)

    spell_id_counter = 0
    spell_string_entries: list[str] = []
    total_pages = 0
    sphere_identity = MOD_POLICY.get("sphere_identity", {})

    for sphere in SPELLBOOK_SPHERES:
        spells = by_sphere[sphere]
        if not spells:
            continue

        sphere_title = sphere_identity.get(sphere, {}).get("title", sphere.capitalize())

        by_rarity: dict[str, list[dict]] = {r: [] for r in RARITY_ORDER}
        for row in spells:
            r = row["_rarity"]
            if r in by_rarity:
                by_rarity[r].append(row)
        for r in RARITY_ORDER:
            by_rarity[r].sort(key=lambda x: x["name"].strip().lower())

        slic_lines = [
            f"// mom_spellbook_{sphere}.slc -- GENERATED by tools/gen_spellbook.py. DO NOT HAND-EDIT.",
            "//",
            f"// Two-tier spellbook for {sphere.upper()} sphere.",
            f"// Tier 1: Hub with rarity filter (Common/Uncommon/Rare/Very Rare/Close).",
            f"// Tier 2: Paged spells per rarity, 3 per page + Prev/Next/Close.",
            "",
        ]

        # --- Tier 1: Hub ---
        hub_name = f"MomSpellHub_{sphere}"
        slic_lines.append(f"// ===== {sphere.upper()} SPELLBOOK HUB =====")
        slic_lines.append(f"alertbox '{hub_name}' {{")
        slic_lines.append(f"    Show();")
        slic_lines.append(f"    Text(ID_MOM_SPELLHUB_{sphere.upper()});")
        slic_lines.append(f"")
        slic_lines.append(f"    Button(ID_MOM_SPELL_CLOSE) {{")
        slic_lines.append(f"        Kill();")
        slic_lines.append(f"    }}")
        for rarity in RARITY_ORDER:
            rarity_key = RARITY_KEYS[rarity]
            if by_rarity[rarity]:
                first_page_name = f"MomSpell_{sphere}_{rarity_key}_1"
                slic_lines.append(f"    // {RARITY_LABELS[rarity]} ({len(by_rarity[rarity])} spells)")
                slic_lines.append(f"    Button(ID_MOM_SPELLHUB_BTN_{rarity_key}) {{")
                slic_lines.append(f"        Kill();")
                slic_lines.append(f"        Message(player[0], '{first_page_name}');")
                slic_lines.append(f"    }}")
        slic_lines.append(f"}}")
        slic_lines.append(f"")

        # --- Tier 2: Paged per rarity ---
        for rarity in RARITY_ORDER:
            rarity_spells = by_rarity[rarity]
            if not rarity_spells:
                continue
            rarity_key = RARITY_KEYS[rarity]
            rarity_label = RARITY_LABELS[rarity]

            pages: list[list[dict]] = []
            for i in range(0, len(rarity_spells), 3):
                pages.append(rarity_spells[i:i+3])
            num_pages = len(pages)
            total_pages += num_pages

            slic_lines.append(f"// ----- {sphere.upper()} / {rarity_label}: {len(rarity_spells)} spells, {num_pages} page(s) -----")
            slic_lines.append(f"")

            for page_idx, page_spells in enumerate(pages):
                page_num = page_idx + 1
                has_prev = page_idx > 0
                has_next = page_idx < num_pages - 1

                alertbox_name = f"MomSpell_{sphere}_{rarity_key}_{page_num}"
                title_key = f"MOM_SPELL_TITLE_{sphere.upper()}_{rarity_key}_{page_num}"

                slic_lines.append(f"// Page {page_num} of {num_pages}")
                slic_lines.append(f"alertbox '{alertbox_name}' {{")
                slic_lines.append(f"    Show();")
                slic_lines.append(f"    Text(ID_{title_key});")
                slic_lines.append(f"")
                slic_lines.append(f"    // Close (back to hub)")
                slic_lines.append(f"    Button(ID_MOM_SPELL_CLOSE) {{")
                slic_lines.append(f"        Kill();")
                slic_lines.append(f"        Message(player[0], '{hub_name}');")
                slic_lines.append(f"    }}")

                if has_prev:
                    prev_name = f"MomSpell_{sphere}_{rarity_key}_{page_num - 1}"
                    slic_lines.append(f"    // Prev")
                    slic_lines.append(f"    Button(ID_MOM_SPELL_PREV) {{")
                    slic_lines.append(f"        Kill();")
                    slic_lines.append(f"        Message(player[0], '{prev_name}');")
                    slic_lines.append(f"    }}")

                for spell_row in page_spells:
                    spell_name = spell_row["name"].strip()
                    shipped_cost = spell_row["_shipped_cost"]
                    str_id = f"ID_MOM_SPELL_{spell_id_counter}"

                    slic_lines.append(f"    // {spell_name} ({shipped_cost} mana)")
                    slic_lines.append(f"    Button({str_id}) {{")
                    slic_lines.append(f"        if (MomMagicCur[player[0]] >= {shipped_cost}) {{")
                    slic_lines.append(f"            MomCastSpell(player[0], {spell_id_counter});")
                    slic_lines.append(f"        }} else {{")
                    slic_lines.append(f"            Message(player[0], 'MomNotEnoughMana');")
                    slic_lines.append(f"        }}")
                    slic_lines.append(f"        Kill();")
                    slic_lines.append(f"    }}")

                    label = f"{spell_name} ({shipped_cost})"
                    label = label.encode("latin-1", errors="replace").decode("latin-1")
                    str_key = f"MOM_SPELL_{spell_id_counter}"
                    spell_string_entries.append(f'{str_key}\t\t"{label}"')
                    spell_id_counter += 1

                if has_next:
                    next_name = f"MomSpell_{sphere}_{rarity_key}_{page_num + 1}"
                    slic_lines.append(f"    // Next")
                    slic_lines.append(f"    Button(ID_MOM_SPELL_NEXT) {{")
                    slic_lines.append(f"        Kill();")
                    slic_lines.append(f"        Message(player[0], '{next_name}');")
                    slic_lines.append(f"    }}")

                slic_lines.append(f"}}")
                slic_lines.append(f"")

        _write_rel(SPELLBOOK_SPHERE_SLC_REL[sphere], "\n".join(slic_lines))

    # --- String entries to scen_str.txt ---
    scen_str_rel = "english/gamedata/scen_str.txt"
    scen_str_path = SCENARIO / scen_str_rel

    str_block_lines = [
        "",
        "# Paged spellbook button labels -- GENERATED by tools/gen_spellbook.py",
        'MOM_SPELL_CLOSE\t\t"Close"',
        'MOM_SPELL_PREV\t\t"<< Prev"',
        'MOM_SPELL_NEXT\t\t"Next >>"',
        'MOM_MSG_SPELL_CAST\t\t"Your spell takes effect."',
        'MOM_MSG_NOT_ENOUGH_MANA\t\t"Not enough mana to cast this spell."',
    ]

    for sphere in SPELLBOOK_SPHERES:
        sphere_title = sphere_identity.get(sphere, {}).get("title", sphere.capitalize())
        str_block_lines.append(f'MOM_SPELLHUB_{sphere.upper()}\t\t"{sphere_title} Spellbook"')

    for rarity in RARITY_ORDER:
        rarity_key = RARITY_KEYS[rarity]
        rarity_label = RARITY_LABELS[rarity]
        str_block_lines.append(f'MOM_SPELLHUB_BTN_{rarity_key}\t\t"{rarity_label}"')

    for sphere in SPELLBOOK_SPHERES:
        sphere_title = sphere_identity.get(sphere, {}).get("title", sphere.capitalize())
        for rarity in RARITY_ORDER:
            rarity_key = RARITY_KEYS[rarity]
            rarity_label = RARITY_LABELS[rarity]
            rarity_spells = [r for r in by_sphere[sphere] if r["_rarity"] == rarity]
            if not rarity_spells:
                continue
            num_pages = (len(rarity_spells) + 2) // 3
            for pg in range(1, num_pages + 1):
                key = f"MOM_SPELL_TITLE_{sphere.upper()}_{rarity_key}_{pg}"
                val = f"{sphere_title} - {rarity_label} ({pg}/{num_pages})"
                str_block_lines.append(f'{key}\t\t"{val}"')

    for sphere in SPELLBOOK_SPHERES:
        greeting = sphere_identity.get(sphere, {}).get("greeting", "")
        if greeting:
            str_block_lines.append(f'MOM_SPHERE_GREETING_{sphere.upper()}\t\t"{greeting}"')

    str_block_lines.extend(spell_string_entries)
    str_block_lines.append("")

    existing = ""
    if scen_str_path.exists():
        with open(scen_str_path, "r", encoding="latin-1", newline="") as fh:
            existing = fh.read()

    marker = "# Paged spellbook button labels -- GENERATED by tools/gen_spellbook.py"
    if marker in existing:
        idx = existing.index(marker)
        while idx > 0 and existing[idx - 1] == "\n":
            idx -= 1
        existing = existing[:idx]

    new_content = existing.rstrip("\n") + "\n" + "\n".join(str_block_lines)
    with open(scen_str_path, "w", encoding="latin-1", newline="") as fh:
        fh.write(new_content)

    legacy_path = SCENARIO / "default/gamedata/mom_spellbook.slc"
    if legacy_path.exists():
        legacy_path.unlink()

    return total_pages, spell_id_counter


def emit_spell_effects() -> int:
    """Emit mom_spellbook_cast.slc: the MomCastSpell if-chain.

    Spell IDs are sequential matching the page numbering from emit_spellbook_pages.
    Effect implementation: summon creates unit, all others are Message stubs.

    Returns the number of spells emitted.
    """
    import re as _re

    rescale_cfg = MOD_POLICY["spellbook"]["cost_rescale"]
    rescale_factor = rescale_cfg["rescale_factor"]
    min_cost = rescale_cfg["min_cost"]
    max_cost = rescale_cfg["max_cost"]
    rarity_factors = rescale_cfg.get("rarity_factors", {})

    spells_path = MOMJR / "spells.csv"
    with open(spells_path, newline="", encoding="utf-8-sig") as fh:
        all_spells = list(csv.DictReader(fh))

    by_sphere: dict[str, list[dict]] = {s: [] for s in SPELLBOOK_SPHERES}
    for row in all_spells:
        sphere = row["sphere"].strip().lower()
        if sphere not in by_sphere:
            continue
        effect_kind = row["effect_kind"].strip()
        overland_cost = int(row["overland_cost"].strip() or "0")
        if effect_kind == "flavour" or overland_cost <= 0:
            continue
        rarity = row.get("rarity", "").lower().strip()
        factor = rarity_factors.get(rarity, rescale_factor)
        shipped_cost = max(min_cost, min(max_cost, int(overland_cost * factor)))
        row["_shipped_cost"] = shipped_cost
        row["_rarity"] = rarity
        by_sphere[sphere].append(row)

    # Sort same as pages: by rarity group then alphabetically within
    ordered_spells = []
    for sphere in SPELLBOOK_SPHERES:
        for rarity in RARITY_ORDER:
            rarity_spells = [r for r in by_sphere[sphere] if r["_rarity"] == rarity]
            rarity_spells.sort(key=lambda x: x["name"].strip().lower())
            ordered_spells.extend(rarity_spells)

    # Build the cast function
    lines = [
        "// mom_spellbook_cast.slc -- GENERATED by tools/gen_spellbook.py. DO NOT HAND-EDIT.",
        "//",
        "// MomCastSpell: generated per-spell effect bodies.",
        "// Spell IDs match the paged alertbox arms (sequential, same order).",
        "// ---------------------------------------------------------------------------",
        "int_f MomCastSpell(int_t p, int_t spellId)",
        "{",
        "    city_t tmpCity;",
        "",
    ]

    # Check which units exist in Units.txt for summon resolution
    units_rel = "default/gamedata/Units.txt"
    units_path = SCENARIO / units_rel
    known_units = set()
    if units_path.exists():
        units_text = units_path.read_text(encoding="latin-1")
        known_units = set(_re.findall(r"^(UNIT_[A-Z0-9_]+)\s*\{", units_text, _re.M))

    def _sanitize(name: str) -> str:
        return _re.sub(r"[^A-Z0-9]", "_", name.upper().strip()).strip("_")

    for idx, row in enumerate(ordered_spells):
        spell_name = row["name"].strip()
        effect_kind = row["effect_kind"].strip()
        shipped_cost = row["_shipped_cost"]
        prefix = "    if" if idx == 0 else "    } elseif"

        lines.append(f"{prefix} (spellId == {idx}) {{")
        lines.append(f"        // {spell_name} ({effect_kind}) - cost {shipped_cost}")
        lines.append(f"        MomMagicCur[p] = MomMagicCur[p] - {shipped_cost};")

        if effect_kind == "summon":
            unit_ident = f"UNIT_{_sanitize(spell_name)}"
            if unit_ident in known_units:
                lines.append(f"        GetCityByIndex(p, 0, tmpCity);")
                lines.append(f"        CreateUnit(p, UnitDB({unit_ident}), tmpCity.location, 0);")
            lines.append(f"        Message(p, 'MomSpellCast');")
        else:
            lines.append(f"        Message(p, 'MomSpellCast');")

    lines.append("    }")
    lines.append("    return 1;")
    lines.append("}")
    lines.append("")

    # Messagebox segments
    lines.append("// Message segments for spell cast feedback")
    lines.append("messagebox 'MomSpellCast' {")
    lines.append("    Show();")
    lines.append("    Text(ID_MOM_MSG_SPELL_CAST);")
    lines.append("}")
    lines.append("")
    lines.append("messagebox 'MomNotEnoughMana' {")
    lines.append("    Show();")
    lines.append("    Text(ID_MOM_MSG_NOT_ENOUGH_MANA);")
    lines.append("}")
    lines.append("")

    _write_rel(SPELLBOOK_CAST_SLC_REL, "\n".join(lines))
    return len(ordered_spells)
